from utils.helper import get_env

S3_ACCESS_KEY = get_env("S3_ACCESS_KEY")
S3_SECRET_ACCESS = get_env("S3_SECRET_ACCESS")
AWS_REGION = get_env("AWS_REGION")
BUCKET_NAME = get_env("BUCKET_NAME")
OPENAI_API_KEY = get_env('OPENAI_API_KEY')
OPENROUTER_API_KEY = get_env('OPENROUTER_API_KEY')
PINECONE_API_KEY = get_env('PINECONE_API_KEY')
TEXT_EXTRACT_ACCESS_KEY = get_env('TEXT_EXTRACT_ACCESS_KEY')
TEXT_EXTRACT_SECRET_ACCESS = get_env('TEXT_EXTRACT_SECRET_ACCESS')